# Generated by Django 4.2.6 on 2023-10-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='starts',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
